apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: "clenimar/application:v0.3"
          command: ["python"]
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 4996
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SCONE_CONFIG_ID
              value: "FlaskSession-23133-13488-7144/flask_restapi"
            - name: SCONE_CAS_ADDR
              value: "4-0-0.scone-cas.cf"
            - name: SCONE_LAS_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SCONE_LOG
              value: "7"
            - name: SCONE_VERSION
              value: "1"
          resources:
            limits:
              "sgx.k8s.io/sgx": 1
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 80
      targetPort: 4996
  selector:
    app.kubernetes.io/name: api
