apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  imagePullSecrets:
   - name: sconeapps
  containers:
    - name: master
      image: sconecuratedimages/apps:redis-4.0.11-alpine-scone4.2.0
      #image: redis
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
