apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-example.fullname" . }}
  labels:
    {{- include "api-example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-example.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-example.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          command: ["python"]
          ports:
            - name: api
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: {{ .Values.redis.service.port | quote }}
            - name: SCONE_CONFIG_ID
              value: {{ .Values.scone.session }}
            - name: SCONE_CAS_ADDR
              value: {{ .Values.scone.cas }}
            - name: SCONE_LAS_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SCONE_LOG
              value: "7"
            - name: SCONE_VERSION
              value: "1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
